model_args:
    model_name: 'resnet_s2s'
    input_size: 60
    output_size: 60
    learning_rate: 0.01
    num_workers: 12
    epochs: 500
    t_max: 500
    only_headline: False
    
data_args:
    batch_size: 32
    train_years: [1979, 1980, 1981, 1982, 1983, 1984, 1985]
    val_years: [1986,1987,1988]
    n_step: 1
    lead_time: 1
    land_vars: ['10m_u_component_of_wind', '10m_v_component_of_wind', '2m_dewpoint_temperature','2m_temperature']
    ocean_vars: []
